title: Portfolio of Eurotek
author: Bensen Xie
email: xiebenshuai@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A great company comes from a set of great people, here is a portfolio of the employees of Eurotek and the projects they have finished 
# social links
github_username:  benshuax

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
